<div class="footer">
	<div class="container main">
		<div class="row">
			<div class="col-md-4">
				<nav>
					<li><a href="">Informations</a></li>
					<li><a href="">Promotions</a></li>
					<li><a href="">Nouveaux produits</a></li>
					<li><a href="">Meilleures ventes</a></li>
					<li><a href="">Nos magasins</a></li>
					<li><a href="">Mon compte</a></li>
					<li><a href="">Contactez-nous</a></li>
				</nav>
				<p>Paiement sécurisé. You can pay using :</p>
				<img class="footer_image"src="./images/payer.jpg" alt="">
			</div>
			<div class="col-md-2 footer_lien">
				<nav>
					<h3>Catégories :</h3>
					<ul>						
						<li><a href="index.php?page=category_list&id_category=1">Heureux</a></li>

							<li><a href="index.php?page=category_list&id_category=2">Cauchemar</a></li>
							<li><a href="index.php?page=category_list&id_category=3">Erotique</a></li>
							<li><a href="index.php?page=category_list&id_category=4">Prémonitoire</a></li>
							<li><a href="index.php?page=category_list&id_category=5">Brisé</a></li>
							<li><a href="index.php?page=category_list&id_category=6">Eveillé</a></li>
							<li><a href="index.php?page=category_list&id_category=7">Merdique</a></li>
					</ul>
				</nav>
			</div>
			<div class="col-md-6 flaticon">
				<a href=""><i class="flaticon-facebook2"></i></a>
				<a href=""><i class="flaticon-twitter"></i></a>
				<a href=""><i class="flaticon-google-plus"></i></a>
				<a href=""><i class="flaticon-instagram19"></i></a>
				<a href=""><i class="flaticon-youtube30"></i></a>

			</div>
		</div>
	</div>
</div>