<div class="header">
	<div class="container main">
		<h1>IDream<img class="imagelogo" src="./images/logo3wa.png" alt=""></h1>
		<nav class="nav_top clearfix">
			<div class="row">
				<div class="col-md-7 col-sm-7 header_lien">
					<ul>
						<li><a href="index.php?page=category_list&id_category=1">Heureux</a></li>
						<li><a href="index.php?page=category_list&id_category=2">Cauchemar</a></li>
						<li><a href="index.php?page=category_list&id_category=3">Erotique</a></li>
						<li><a href="index.php?page=category_list&id_category=4">Prémonitoire</a></li>
						<li><a href="index.php?page=category_list&id_category=5">Brisé</a></li>
						<li><a href="index.php?page=category_list&id_category=6">Eveillé</a></li>
						<li><a href="index.php?page=category_list&id_category=7">Merdique</a></li>
					</ul>
				</div>
				<div class="col-md-3 col-sm-3 login">
					<?php require('apps/header_log.php');?>
				</div>
				<div class="col-md-2 col-sm-2 panier_div">
					<?php require('apps/panier.php');?>
				</div>
				<?php require('./apps/user_add.php'); ?>
			</div>
		</nav>
	</div>
</div>