<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">

	    <title>DreamCommerce - apprendre le travail collaboratif par Git</title>
	    <link rel="stylesheet" href="views/styles/reset.css">
	    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="views/styles/jquery.bxslider.css">
		<link rel="stylesheet" href="views/fonts/flaticon.css">
	    <link rel="stylesheet" href="views/styles/bootstrap.min.css">
	    <link rel="stylesheet" href="views/styles/style.css">
	    <!-- <link rel="stylesheet" type="text/css" href="views/styles/flaticon.css">  -->
	    <script type="text/javascript" src="apps/scripts/bootstrap.min.js"></script>
	    <script type="text/javascript" src="apps/scripts/scripts.js"></script>
	</head>
	<body>
	<div class="wrap">
		<header>
				<?php require('apps/header.php'); ?>
		</header>
		<div class="container main">
			<section>
				<?php require('apps/content.php'); ?>
			</section>
		</div>
	</div>
		<footer>
				<?php require('apps/footer.php'); ?>
		</footer>
		<script type="text/javascript" src="./views/tinymce/tinymce.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){ /*Que l'on peut résumer par : $(function(){ */
				tinymce.init({
				    selector: "textarea.mce"
				 });
				});
		</script>
			<!-- jQuery library (served from Google) -->
		<script type="text/javascript" src="apps/scripts/jquery.bxslider.min.js"></script>
		<script>
			$(document).ready(function(){ /*Que l'on peut résumer par : $(function(){ */
				$('.caroussel').bxSlider({
					mode: "fade"
					// startSlide
				});
			});
		</script>
	</body>
</html>